import puppeteer from "puppeteer";
const b=await puppeteer.launch({headless:"new",args:["--no-sandbox"],protocolTimeout:180000});
const p=await b.newPage();
await p.setViewport({width:1440,height:900});
p.on("pageerror",e=>console.log("PAGEERROR:",String(e).split("\n")[0]));
p.on("console",m=>console.log("CONSOLE["+m.type()+"]:",m.text().slice(0,160)));
await p.setRequestInterception(true);
p.on("request",r=>{const u=r.url();
  if(r.method()==="OPTIONS")return r.respond({status:204,headers:{"access-control-allow-origin":"*","access-control-allow-headers":"*","access-control-allow-methods":"*"}});
  if(/cdn\.jsdelivr|fonts\./.test(u))return r.respond({status:200,headers:{"content-type":"text/css"},body:""});
  if(/supabase\.co/.test(u))return r.respond({status:200,headers:{"access-control-allow-origin":"*","content-type":"application/json"},body:"[]"});
  r.continue();});
await p.goto("http://localhost:8080/p-message.html",{waitUntil:"domcontentloaded"});
await new Promise(r=>setTimeout(r,4000));
console.log("--- screenshot only ---");
await p.screenshot({path:"tests/shot_pm_desktop.png"});
console.log("ok");
await b.close();
