// =====================================================================
// Anthropic tool schemas for the per-tenant web agent. The names &
// parameters mirror the n8n webhook paths exactly so dispatch is a
// trivial name → URL map.
// =====================================================================

export type ToolDef = {
  name: string;
  description: string;
  input_schema: Record<string, unknown>;
  webhook_path: string;          // appended to N8N_WEBHOOK_BASE
};

const str  = { type: "string" };
const num  = { type: "number" };
const bool = { type: "boolean" };
const obj  = { type: "object" };

export const TOOLS: ToolDef[] = [
  // ----- Booking core (workflow 01) ------------------------------
  { name: "search_trips",
    description: "Search available bus trips between two cities on a specific date.",
    webhook_path: "/webhook/vapi/search-trips",
    input_schema: { type: "object", required: ["origin","destination","date"],
      properties: { origin: str, destination: str, date: str } } },
  { name: "check_seats",
    description: "List available seat numbers for a given trip. Optional preference for window seats.",
    webhook_path: "/webhook/vapi/check-seats",
    input_schema: { type: "object", required: ["trip_id"],
      properties: { trip_id: num, prefer_window: bool } } },
  { name: "hold_seat",
    description: "Reserve a specific seat for 10 minutes pending payment. Returns booking_ref.",
    webhook_path: "/webhook/vapi/hold-seat",
    input_schema: { type: "object", required: ["trip_id","seat_number","passenger_name","phone"],
      properties: { trip_id: num, seat_number: num, passenger_name: str, phone: str,
                    id_type: str, id_number: str, payment_method: str } } },
  { name: "initiate_payment",
    description: "Send a USSD push payment request to the customer's phone for a HELD booking.",
    webhook_path: "/webhook/vapi/initiate-payment",
    input_schema: { type: "object", required: ["booking_ref","phone"],
      properties: { booking_ref: str, phone: str, alt_payment_phone: str, payment_method: str } } },
  { name: "cancel_booking",
    description: "Cancel a booking. Apply 75% refund or free reschedule policy depending on time-to-departure.",
    webhook_path: "/webhook/vapi/cancel-booking",
    input_schema: { type: "object", required: ["booking_ref"],
      properties: { booking_ref: str, choice: str } } },
  { name: "nearest_hub",
    description: "Find the nearest serviced hub for an unserved district and log the gap.",
    webhook_path: "/webhook/vapi/nearest-hub",
    input_schema: { type: "object", required: ["district"],
      properties: { district: str, region: str } } },
  { name: "escalate",
    description: "Log a complaint and trigger manager notification.",
    webhook_path: "/webhook/vapi/escalate",
    input_schema: { type: "object", required: ["summary"],
      properties: { booking_ref: str, phone: str, summary: str } } },
  { name: "find_next_available",
    description: "Find upcoming trips with available seats from a given datetime onwards.",
    webhook_path: "/webhook/vapi/find-next-available",
    input_schema: { type: "object", required: ["origin","destination"],
      properties: { origin: str, destination: str, from_datetime: str, limit: num, seats_needed: num } } },
  { name: "hold_next_available",
    description: "Find the next trip and immediately hold a seat for the passenger in one step.",
    webhook_path: "/webhook/vapi/hold-next-available",
    input_schema: { type: "object", required: ["origin","destination","passenger_name","phone"],
      properties: { origin: str, destination: str, passenger_name: str, phone: str,
                    from_datetime: str, prefer_window: bool, payment_method: str,
                    id_type: str, id_number: str, max_lookahead: num } } },

  // ----- Cargo (workflow 01b) ------------------------------------
  { name: "find_buses_for_route",
    description: "Find which buses run a parcel route (origin → destination).",
    webhook_path: "/webhook/vapi/find-buses-for-route",
    input_schema: { type: "object", required: ["origin","destination"],
      properties: { origin: str, destination: str } } },
  { name: "find_agents",
    description: "List cargo agents in a region (and optional terminal).",
    webhook_path: "/webhook/vapi/find-agents",
    input_schema: { type: "object", required: ["region"],
      properties: { region: str, terminal: str } } },
  { name: "track_shipment",
    description: "Look up parcel status by tracking_code or phone (sender or receiver).",
    webhook_path: "/webhook/vapi/track-shipment",
    input_schema: { type: "object",
      properties: { tracking_code: str, phone: str } } },
  { name: "compute_freight_quote",
    description: "Compute and store a freight quote. Returns quote_ref valid 24h.",
    webhook_path: "/webhook/vapi/compute-freight-quote",
    input_schema: { type: "object", required: ["weight_kg","declared_value_tzs","size"],
      properties: { weight_kg: num, declared_value_tzs: num, size: { type: "string", enum: ["small","medium","large"] },
                    sender_phone: str, origin_region: str, destination_region: str } } },
  { name: "register_shipment",
    description: "Register a new parcel shipment after the customer accepts a quote. Returns tracking_code.",
    webhook_path: "/webhook/vapi/register-shipment",
    input_schema: { type: "object",
      required: ["sender_name","sender_phone","sender_region","receiver_name","receiver_phone",
                 "receiver_region","product_description","weight_kg","bus_name","bus_route","bus_departure"],
      properties: { sender_name: str, sender_phone: str, sender_region: str,
                    receiver_name: str, receiver_phone: str, receiver_region: str,
                    product_description: str, weight_kg: num, declared_value_tzs: num,
                    bus_name: str, bus_route: str, bus_departure: str,
                    agent_origin_name: str, agent_origin_phone: str,
                    agent_destination_name: str, agent_destination_phone: str } } },

  // ----- Proactive ------------------------------------------------
  { name: "send_sms",
    description: "Send an SMS to a phone via Africa's Talking. Use for tickets, tracking codes, payment instructions.",
    webhook_path: "/webhook/vapi/send-sms",
    input_schema: { type: "object", required: ["to","message"],
      properties: { to: str, message: str, related_ref: str } } },
  { name: "send_whatsapp",
    description: "Send a WhatsApp message via Africa's Talking. Use for photos and longer details.",
    webhook_path: "/webhook/vapi/send-whatsapp",
    input_schema: { type: "object", required: ["to","message"],
      properties: { to: str, message: str, related_ref: str } } },
  { name: "trigger_outbound_call",
    description: "Queue an outbound call back to a customer's phone via VAPI. Fires within 30 seconds.",
    webhook_path: "/webhook/vapi/trigger-outbound-call",
    input_schema: { type: "object", required: ["to","purpose"],
      properties: { to: str, purpose: str, ticket_code: str, context: obj } } },
  { name: "schedule_reminder",
    description: "Schedule a future SMS / WhatsApp / call to a customer at a specific timestamp.",
    webhook_path: "/webhook/vapi/schedule-reminder",
    input_schema: { type: "object", required: ["phone","channel","fire_at"],
      properties: { phone: str, channel: { type: "string", enum: ["sms","whatsapp","call"] },
                    message: str, fire_at: str, booking_ref: str, tracking_code: str } } },
  { name: "get_bus_photo",
    description: "Look up bus photos by plate / bus_id / trip_id. Returns URLs.",
    webhook_path: "/webhook/vapi/get-bus-photo",
    input_schema: { type: "object",
      properties: { plate: str, bus_id: num, trip_id: num } } },

  // ----- Manager / operational -----------------------------------
  { name: "today_bookings_summary",
    description: "Counts of held / confirmed / cancelled bookings + revenue for today.",
    webhook_path: "/webhook/vapi/today-bookings-summary",
    input_schema: { type: "object", properties: {} } },
  { name: "revenue_summary",
    description: "Total revenue between two dates.",
    webhook_path: "/webhook/vapi/revenue-summary",
    input_schema: { type: "object",
      properties: { start_date: str, end_date: str } } },
  { name: "pending_holds",
    description: "List bookings still in HELD status with time remaining.",
    webhook_path: "/webhook/vapi/pending-holds",
    input_schema: { type: "object", properties: {} } },
  { name: "service_gap_report",
    description: "Top requested districts where the company doesn't yet operate.",
    webhook_path: "/webhook/vapi/service-gap-report",
    input_schema: { type: "object", properties: {} } },
  { name: "customer_history",
    description: "Pull a customer's booking history by phone for returning-caller recognition.",
    webhook_path: "/webhook/vapi/customer-history",
    input_schema: { type: "object", required: ["phone"],
      properties: { phone: str } } },
];

export const TOOL_BY_NAME: Record<string, ToolDef> =
  Object.fromEntries(TOOLS.map(t => [t.name, t]));
